### ISSUE TITLE
Use Title when presenting

### ISSUE THREAD

**Issue by niclash** [Sensetif/sensetif-app-plugin#55]
In Datapoint, the Project and Subsystem names are used. Change to use "Title"

![image](https://github.com/Sensetif/sensetif-app-plugin/assets/106693/f1074145-9ed9-40f3-bc76-00fba15d4f62)

**Comment by grzegorekb** [comment]
Currently it works in a way that `project name` and `subsystem name` are passed in url, eg:
`/a/sensetif-app?tab=edit_datapoint&project=l2w-test-app&subsystem=room3&datapoint=battery`

We have an endpoint `get_datapoint` which takes `project_name` and `subsystem_name`.

In order to render title of project and subsystem I would need to either:
1. Extend `get_datapoint` endpoint so it also returns that data (project/subsystem title)
2. Make 2 additional API calls to fetch project & subtitle

**Comment by niclash** [comment]
Closing this for now. I am entering a TODO in the source code for changes when Caching is done (maybe never).
